// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow to explain a step in an algorithm.
 *
 * - explainStep - A function that handles the step explanation process.
 * - ExplainStepInput - The input type for the explainStep function.
 * - ExplainStepOutput - The return type for the explainStep function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainStepInputSchema = z.object({
  code: z.string().describe('The code of the algorithm.'),
  currentLine: z.number().describe('The current line number being executed.'),
  variables: z.string().describe('The JSON stringified current state of the variables.'),
});
export type ExplainStepInput = z.infer<typeof ExplainStepInputSchema>;

const ExplainStepOutputSchema = z.object({
  explanation: z.string().describe('A short, clear, one-sentence explanation of the current step. Explain it like you are a friendly teacher.'),
});
export type ExplainStepOutput = z.infer<typeof ExplainStepOutputSchema>;

export async function explainStep(input: ExplainStepInput): Promise<ExplainStepOutput> {
  return explainStepFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainStepPrompt',
  input: {schema: ExplainStepInputSchema},
  output: {schema: ExplainStepOutputSchema},
  prompt: `You are an expert algorithm explainer. You are able to explain complex algorithms in simple terms for a beginner.

You will be given the full code of a sorting algorithm, the line number that is currently being executed, and the current state of the variables.

Your task is to provide a short, one-sentence explanation of what is happening in the current step. Focus on what the code is doing with the variables. Be concise and clear.

For example, if the line is 'if (arr[j] > arr[j + 1])' and the variables show that arr[j] is 8 and arr[j+1] is 4, a good explanation would be: "The code is checking if the element at index j (value 8) is greater than the element at index j+1 (value 4)."

---
Algorithm Code:
\`\`\`javascript
{{code}}
\`\`\`

Current Line: {{currentLine}}

Current Variables:
\`\`\`json
{{variables}}
\`\`\`

Please provide your one-sentence explanation.
  `,
});

const explainStepFlow = ai.defineFlow(
  {
    name: 'explainStepFlow',
    inputSchema: ExplainStepInputSchema,
    outputSchema: ExplainStepOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
